const COLOR_MAP: Record<string, string> = {
  "BLACK": "黑色",
  "WHITE": "白色",
  "OFF WHITE": "米白",
  "NATURAL": "原色",
  "ECRU": "本白",
  "IVORY": "象牙白",
  "CREAM": "奶油白",
  "NAVY": "深藍",
  "BLUE": "藍色",
  "LIGHT BLUE": "淺藍",
  "DARK BLUE": "深藍",
  "NAVY BLUE": "海軍藍",
  "SKY BLUE": "天空藍",
  "COBALT BLUE": "鈷藍",
  "GRAY": "灰色",
  "GREY": "灰色",
  "DARK GRAY": "深灰",
  "LIGHT GRAY": "淺灰",
  "SILVER GRAY": "銀灰",
  "CHARCOAL GRAY": "炭灰",
  "RED": "紅色",
  "DARK RED": "深紅",
  "BRICK RED": "磚紅",
  "WINE": "酒紅",
  "BORDEAUX": "波爾多紅",
  "PINK": "粉紅",
  "LIGHT PINK": "淺粉",
  "DARK PINK": "深粉",
  "HOT PINK": "桃紅",
  "SALMON PINK": "鮭魚粉",
  "PURPLE": "紫色",
  "DARK PURPLE": "深紫",
  "LIGHT PURPLE": "淡紫",
  "LAVENDER": "薰衣草紫",
  "GREEN": "綠色",
  "DARK GREEN": "深綠",
  "LIGHT GREEN": "淺綠",
  "OLIVE": "橄欖綠",
  "KHAKI": "卡其",
  "SAGE": "鼠尾草綠",
  "MINT": "薄荷綠",
  "YELLOW GREEN": "黃綠",
  "BROWN": "棕色",
  "DARK BROWN": "深棕",
  "LIGHT BROWN": "淺棕",
  "CAMEL": "駝色",
  "TAN": "棕褐",
  "YELLOW": "黃色",
  "LIGHT YELLOW": "淺黃",
  "MUSTARD": "芥黃",
  "ORANGE": "橘色",
  "DARK ORANGE": "深橘",
  "BEIGE": "米色",
  "DARK BEIGE": "深米",
  "LIGHT BEIGE": "淺米",
  "GREIGE": "灰米",
  "MOCHA": "摩卡",
}

export function toChineseColor(name: string): string {
  const upper = name.toUpperCase().trim()
  return COLOR_MAP[upper] ?? name
}
